In [11]:
import pyarrow.parquet as pq
import pandas as pd

obs = pq.read_table("data/observations/Seattle.parquet").to_pandas()
obs.tail(25)

,station,observed_at_local,temperature_f,temperature_c,scraped_at_utc,precipitation_hourly_in,precipitation_total_in
281308,Seattle,2026-01-30T23:53:00-08:00,49,9,2026-02-01T08:13:03.508556+00:00,None,None
281309,Seattle,2026-01-31T00:53:00-08:00,49,9,2026-02-01T08:13:03.508556+00:00,None,None
281310,Seattle,2026-01-31T01:53:00-08:00,50,10,2026-02-01T08:13:03.508556+00:00,None,None
281311,Seattle,2026-01-31T02:53:00-08:00,49,9,2026-02-01T08:13:03.508556+00:00,None,None
281312,Seattle,2026-01-31T03:53:00-08:00,48,9,2026-02-01T08:13:03.508556+00:00,None,None
281313,Seattle,2026-01-31T04:53:00-08:00,48,9,2026-02-01T08:13:03.508556+00:00,None,None
281314,Seattle,2026-01-31T05:53:00-08:00,47,8,2026-02-01T08:13:03.508556+00:00,None,None
281315,Seattle,2026-01-31T06:53:00-08:00,48,9,2026-02-01T08:13:03.508556+00:00,None,None
281316,Seattle,2026-01-31T07:53:00-08:00,48,9,2026-02-01T08:13:03.508556+00:00,None,None
281317,Seattle,2026-01-31T08:12:00-08:00,48,9,2026-02-01T08:13:03.508556+00:00,None,None
281318,Seattle,2026-01-31T08:53:00-08:00,51,11,2026-02-01T08:13:03.508556+00:00,None,None
281319,Seattle,2026-01-31T09:53:00-08:00,51,11,2026-02-01T08:13:03.508556+00:00,None,None
281320,Seattle,2026-01-31T10:53:00-08:00,50,10,2026-02-01T08:13:03.508556+00:00,None,None
281321,Seattle,2026-01-31T11:53:00-08:00,53,12,2026-02-01T08:13:03.508556+00:00,None,None
281322,Seattle,2026-01-31T12:53:00-08:00,54,12,2026-02-01T08:13:03.508556+00:00,None,None
281323,Seattle,2026-01-31T13:53:00-08:00,55,13,2026-02-01T08:13:03.508556+00:00,None,None
281324,Seattle,2026-01-31T14:53:00-08:00,57,14,2026-02-01T08:13:03.508556+00:00,None,None
281325,Seattle,2026-01-31T15:53:00-08:00,56,13,2026-02-01T08:13:03.508556+00:00,None,None
281326,Seattle,2026-01-31T16:53:00-08:00,54,12,2026-02-01T08:13:03.508556+00:00,None,None
281327,Seattle,2026-01-31T17:53:00-08:00,50,10,2026-02-01T08:13:03.508556+00:00,None,None
281328,Seattle,2026-01-31T18:53:00-08:00,50,10,2026-02-01T08:13:03.508556+00:00,None,None
281329,Seattle,2026-01-31T19:53:00-08:00,50,10,2026-02-01T08:13:03.508556+00:00,None,None
281330,Seattle,2026-01-31T20:53:00-08:00,51,11,2026-02-01T08:13:03.508556+00:00,None,None
281331,Seattle,2026-01-31T21:53:00-08:00,50,10,2026-02-01T08:13:03.508556+00:00,None,None
281332,Seattle,2026-01-31T22:53:00-08:00,49,9,2026-02-01T08:13:03.508556+00:00,None,None

In [14]:
bias_df = pq.read_table("data/analysis_data/daily_bias_raw/temperature_station_daily_biases_raw_20260114_20260201.parquet").to_pandas()
bias_df[(bias_df["City"] == "London") & (bias_df["model"] == "ecmwf-hres") & (bias_df["date_str"] == "20260131")]

,City,date_str,horizon_hours,forecast_max,observed_temp,bias,model
4331,London,20260131,120,6.85,11,-4.15,ecmwf-hres
4336,London,20260131,114,6.85,11,-4.15,ecmwf-hres
4341,London,20260131,108,8.85,11,-2.15,ecmwf-hres
4346,London,20260131,102,8.85,11,-2.15,ecmwf-hres
4350,London,20260131,96,9.85,11,-1.15,ecmwf-hres
4355,London,20260131,90,8.85,11,-2.15,ecmwf-hres
4360,London,20260131,84,9.85,11,-1.15,ecmwf-hres
4365,London,20260131,78,7.85,11,-3.15,ecmwf-hres
4369,London,20260131,72,9.85,11,-1.15,ecmwf-hres
4373,London,20260131,66,9.85,11,-1.15,ecmwf-hres
4377,London,20260131,60,9.85,11,-1.15,ecmwf-hres
4381,London,20260131,54,8.85,11,-2.15,ecmwf-hres
4384,London,20260131,48,9.85,11,-1.15,ecmwf-hres
4387,London,20260131,42,9.85,11,-1.15,ecmwf-hres
4390,London,20260131,36,8.85,11,-2.15,ecmwf-hres
4392,London,20260131,24,8.85,11,-2.15,ecmwf-hres
4394,London,20260131,18,9.85,11,-1.15,ecmwf-hres
4396,London,20260131,12,9.85,11,-1.15,ecmwf-hres

In [18]:
gfs_2026012900 = pq.read_table("data/point_data/gfs/raw/gfs_2026013000_2026020300.parquet").to_pandas()
df_nyc = gfs_2026012900[gfs_2026012900["City"] == "NYC"].copy()

df_nyc["Temperature2m_F"] = (
    ((df_nyc["Temperature2m"] - 273.15) * 9/5 + 32)
    .round(0)
    .astype(int)
)

df_nyc["TemperatureStation_F"] = (
    ((df_nyc["TemperatureStation"] - 273.15) * 9/5 + 32)
    .round(0)
    .astype(int)
)

df_nyc[[
    "City",
    "InitTimeUTC",
    "ValidTimeUTC",
    "ValidTimeLocal",
    "LeadHour",
    "Temperature2m_F",
    "TemperatureStation_F"
]]

,City,InitTimeUTC,ValidTimeUTC,ValidTimeLocal,LeadHour,Temperature2m_F,TemperatureStation_F
165,NYC,2026-01-30 00:00:00+00:00,2026-01-30 00:00:00+00:00,2026-01-29T19:00:00-05:00,0,14,14
166,NYC,2026-01-30 00:00:00+00:00,2026-01-30 03:00:00+00:00,2026-01-29T22:00:00-05:00,3,10,10
167,NYC,2026-01-30 00:00:00+00:00,2026-01-30 06:00:00+00:00,2026-01-30T01:00:00-05:00,6,7,7
168,NYC,2026-01-30 00:00:00+00:00,2026-01-30 09:00:00+00:00,2026-01-30T04:00:00-05:00,9,5,5
169,NYC,2026-01-30 00:00:00+00:00,2026-01-30 12:00:00+00:00,2026-01-30T07:00:00-05:00,12,1,1
170,NYC,2026-01-30 00:00:00+00:00,2026-01-30 15:00:00+00:00,2026-01-30T10:00:00-05:00,15,8,8
171,NYC,2026-01-30 00:00:00+00:00,2026-01-30 18:00:00+00:00,2026-01-30T13:00:00-05:00,18,14,14
172,NYC,2026-01-30 00:00:00+00:00,2026-01-30 21:00:00+00:00,2026-01-30T16:00:00-05:00,21,14,14
173,NYC,2026-01-30 00:00:00+00:00,2026-01-31 00:00:00+00:00,2026-01-30T19:00:00-05:00,24,8,8
174,NYC,2026-01-30 00:00:00+00:00,2026-01-31 03:00:00+00:00,2026-01-30T22:00:00-05:00,27,5,5
175,NYC,2026-01-30 00:00:00+00:00,2026-01-31 06:00:00+00:00,2026-01-31T01:00:00-05:00,30,-1,-1
176,NYC,2026-01-30 00:00:00+00:00,2026-01-31 09:00:00+00:00,2026-01-31T04:00:00-05:00,33,-4,-4
177,NYC,2026-01-30 00:00:00+00:00,2026-01-31 12:00:00+00:00,2026-01-31T07:00:00-05:00,36,-6,-6
178,NYC,2026-01-30 00:00:00+00:00,2026-01-31 15:00:00+00:00,2026-01-31T10:00:00-05:00,39,8,8
179,NYC,2026-01-30 00:00:00+00:00,2026-01-31 18:00:00+00:00,2026-01-31T13:00:00-05:00,42,16,16
180,NYC,2026-01-30 00:00:00+00:00,2026-01-31 21:00:00+00:00,2026-01-31T16:00:00-05:00,45,17,17
181,NYC,2026-01-30 00:00:00+00:00,2026-02-01 00:00:00+00:00,2026-01-31T19:00:00-05:00,48,14,14
182,NYC,2026-01-30 00:00:00+00:00,2026-02-01 03:00:00+00:00,2026-01-31T22:00:00-05:00,51,14,14
183,NYC,2026-01-30 00:00:00+00:00,2026-02-01 06:00:00+00:00,2026-02-01T01:00:00-05:00,54,14,14
184,NYC,2026-01-30 00:00:00+00:00,2026-02-01 09:00:00+00:00,2026-02-01T04:00:00-05:00,57,10,10
185,NYC,2026-01-30 00:00:00+00:00,2026-02-01 12:00:00+00:00,2026-02-01T07:00:00-05:00,60,12,12
186,NYC,2026-01-30 00:00:00+00:00,2026-02-01 15:00:00+00:00,2026-02-01T10:00:00-05:00,63,14,14
187,NYC,2026-01-30 00:00:00+00:00,2026-02-01 18:00:00+00:00,2026-02-01T13:00:00-05:00,66,19,19
188,NYC,2026-01-30 00:00:00+00:00,2026-02-01 21:00:00+00:00,2026-02-01T16:00:00-05:00,69,21,21
189,NYC,2026-01-30 00:00:00+00:00,2026-02-02 00:00:00+00:00,2026-02-01T19:00:00-05:00,72,17,17
190,NYC,2026-01-30 00:00:00+00:00,2026-02-02 03:00:00+00:00,2026-02-01T22:00:00-05:00,75,14,14
191,NYC,2026-01-30 00:00:00+00:00,2026-02-02 06:00:00+00:00,2026-02-02T01:00:00-05:00,78,12,12
192,NYC,2026-01-30 00:00:00+00:00,2026-02-02 09:00:00+00:00,2026-02-02T04:00:00-05:00,81,12,12
193,NYC,2026-01-30 00:00:00+00:00,2026-02-02 12:00:00+00:00,2026-02-02T07:00:00-05:00,84,10,10
194,NYC,2026-01-30 00:00:00+00:00,2026-02-02 15:00:00+00:00,2026-02-02T10:00:00-05:00,87,21,21
195,NYC,2026-01-30 00:00:00+00:00,2026-02-02 18:00:00+00:00,2026-02-02T13:00:00-05:00,90,28,28
196,NYC,2026-01-30 00:00:00+00:00,2026-02-02 21:00:00+00:00,2026-02-02T16:00:00-05:00,93,28,28
197,NYC,2026-01-30 00:00:00+00:00,2026-02-03 00:00:00+00:00,2026-02-02T19:00:00-05:00,96,23,23

In [6]:
gfs_2026012900[gfs_2026012900["City"] == "Ankara"]

,City,InitTimeUTC,ValidTimeUTC,ValidTimeLocal,Timezone,LeadHour,StationElevation,Temperature2m,Temperature1000mb,Temperature925mb,Temperature850mb,Temperature700mb,TemperatureStation
0,Ankara,2026-01-31 00:00:00+00:00,2026-01-31 00:00:00+00:00,2026-01-31T03:00:00+03:00,Europe/Istanbul,0,949.1472,276,283,279,276,266,276
1,Ankara,2026-01-31 00:00:00+00:00,2026-01-31 03:00:00+00:00,2026-01-31T06:00:00+03:00,Europe/Istanbul,3,949.1472,276,283,279,276,266,276
2,Ankara,2026-01-31 00:00:00+00:00,2026-01-31 06:00:00+00:00,2026-01-31T09:00:00+03:00,Europe/Istanbul,6,949.1472,276,284,279,276,266,276
3,Ankara,2026-01-31 00:00:00+00:00,2026-01-31 09:00:00+00:00,2026-01-31T12:00:00+03:00,Europe/Istanbul,9,949.1472,280,287,282,277,266,278
4,Ankara,2026-01-31 00:00:00+00:00,2026-01-31 12:00:00+00:00,2026-01-31T15:00:00+03:00,Europe/Istanbul,12,949.1472,278,285,281,276,268,277
5,Ankara,2026-01-31 00:00:00+00:00,2026-01-31 15:00:00+00:00,2026-01-31T18:00:00+03:00,Europe/Istanbul,15,949.1472,277,284,280,277,267,277
6,Ankara,2026-01-31 00:00:00+00:00,2026-01-31 18:00:00+00:00,2026-01-31T21:00:00+03:00,Europe/Istanbul,18,949.1472,277,285,281,278,267,277
7,Ankara,2026-01-31 00:00:00+00:00,2026-01-31 21:00:00+00:00,2026-02-01T00:00:00+03:00,Europe/Istanbul,21,949.1472,278,285,281,277,266,277
8,Ankara,2026-01-31 00:00:00+00:00,2026-02-01 00:00:00+00:00,2026-02-01T03:00:00+03:00,Europe/Istanbul,24,949.1472,276,284,279,276,267,276
9,Ankara,2026-01-31 00:00:00+00:00,2026-02-01 03:00:00+00:00,2026-02-01T06:00:00+03:00,Europe/Istanbul,27,949.1472,276,283,279,276,267,276
10,Ankara,2026-01-31 00:00:00+00:00,2026-02-01 06:00:00+00:00,2026-02-01T09:00:00+03:00,Europe/Istanbul,30,949.1472,276,284,280,276,268,276
11,Ankara,2026-01-31 00:00:00+00:00,2026-02-01 09:00:00+00:00,2026-02-01T12:00:00+03:00,Europe/Istanbul,33,949.1472,281,288,283,278,269,279
12,Ankara,2026-01-31 00:00:00+00:00,2026-02-01 12:00:00+00:00,2026-02-01T15:00:00+03:00,Europe/Istanbul,36,949.1472,283,289,285,279,269,281
13,Ankara,2026-01-31 00:00:00+00:00,2026-02-01 15:00:00+00:00,2026-02-01T18:00:00+03:00,Europe/Istanbul,39,949.1472,281,289,285,280,270,280
14,Ankara,2026-01-31 00:00:00+00:00,2026-02-01 18:00:00+00:00,2026-02-01T21:00:00+03:00,Europe/Istanbul,42,949.1472,280,288,283,280,270,280
15,Ankara,2026-01-31 00:00:00+00:00,2026-02-01 21:00:00+00:00,2026-02-02T00:00:00+03:00,Europe/Istanbul,45,949.1472,281,288,284,279,269,280
16,Ankara,2026-01-31 00:00:00+00:00,2026-02-02 00:00:00+00:00,2026-02-02T03:00:00+03:00,Europe/Istanbul,48,949.1472,279,286,282,277,268,277
17,Ankara,2026-01-31 00:00:00+00:00,2026-02-02 03:00:00+00:00,2026-02-02T06:00:00+03:00,Europe/Istanbul,51,949.1472,276,283,279,275,266,275
18,Ankara,2026-01-31 00:00:00+00:00,2026-02-02 06:00:00+00:00,2026-02-02T09:00:00+03:00,Europe/Istanbul,54,949.1472,276,283,279,274,267,275
19,Ankara,2026-01-31 00:00:00+00:00,2026-02-02 09:00:00+00:00,2026-02-02T12:00:00+03:00,Europe/Istanbul,57,949.1472,280,286,282,277,267,278
20,Ankara,2026-01-31 00:00:00+00:00,2026-02-02 12:00:00+00:00,2026-02-02T15:00:00+03:00,Europe/Istanbul,60,949.1472,280,287,283,277,267,278
21,Ankara,2026-01-31 00:00:00+00:00,2026-02-02 15:00:00+00:00,2026-02-02T18:00:00+03:00,Europe/Istanbul,63,949.1472,280,287,283,278,267,279
22,Ankara,2026-01-31 00:00:00+00:00,2026-02-02 18:00:00+00:00,2026-02-02T21:00:00+03:00,Europe/Istanbul,66,949.1472,278,285,281,276,266,277
23,Ankara,2026-01-31 00:00:00+00:00,2026-02-02 21:00:00+00:00,2026-02-03T00:00:00+03:00,Europe/Istanbul,69,949.1472,277,284,280,275,265,276
24,Ankara,2026-01-31 00:00:00+00:00,2026-02-03 00:00:00+00:00,2026-02-03T03:00:00+03:00,Europe/Istanbul,72,949.1472,275,282,277,273,264,273
25,Ankara,2026-01-31 00:00:00+00:00,2026-02-03 03:00:00+00:00,2026-02-03T06:00:00+03:00,Europe/Istanbul,75,949.1472,274,280,276,271,263,272
26,Ankara,2026-01-31 00:00:00+00:00,2026-02-03 06:00:00+00:00,2026-02-03T09:00:00+03:00,Europe/Istanbul,78,949.1472,273,280,276,271,263,272
27,Ankara,2026-01-31 00:00:00+00:00,2026-02-03 09:00:00+00:00,2026-02-03T12:00:00+03:00,Europe/Istanbul,81,949.1472,275,281,277,271,263,273
28,Ankara,2026-01-31 00:00:00+00:00,2026-02-03 12:00:00+00:00,2026-02-03T15:00:00+03:00,Europe/Istanbul,84,949.1472,277,283,278,273,262,274
29,Ankara,2026-01-31 00:00:00+00:00,2026-02-03 15:00:00+00:00,2026-02-03T18:00:00+03:00,Europe/Istanbul,87,949.1472,275,281,277,271,261,273
30,Ankara,2026-01-31 00:00:00+00:00,2026-02-03 18:00:00+00:00,2026-02-03T21:00:00+03:00,Europe/Istanbul,90,949.1472,273,279,275,270,261,271
31,Ankara,2026-01-31 00:00:00+00:00,2026-02-03 21:00:00+00:00,2026-02-04T00:00:00+03:00,Europe/Istanbul,93,949.1472,272,278,274,269,261,270
32,Ankara,2026-01-31 00:00:00+00:00,2026-02-04 00:00:00+00:00,2026-02-04T03:00:00+03:00,Europe/Istanbul,96,949.1472,272,278,274,269,262,270

In [12]:
import pyarrow.parquet as pq
df = pq.read_table("data/analysis_data/daily_bias_raw/temperature_station_daily_biases_raw_20260114_20260131.parquet").to_pandas()
df[(df["City"] == "Ankara") & (df["date_str"] == "20260130") & (df["model"] == "gfs")].tail(25)

       City  date_str  horizon_hours  forecast_max  observed_temp  bias model
224  Ankara  20260130            117          4.85             11 -6.15   gfs
229  Ankara  20260130            111          4.85             11 -6.15   gfs
234  Ankara  20260130            105          4.85             11 -6.15   gfs
239  Ankara  20260130             99          4.85             11 -6.15   gfs
243  Ankara  20260130             93          5.85             11 -5.15   gfs
248  Ankara  20260130             87          6.85             11 -4.15   gfs
253  Ankara  20260130             81          4.85             11 -6.15   gfs
258  Ankara  20260130             75          4.85             11 -6.15   gfs
262  Ankara  20260130             69          5.85             11 -5.15   gfs
266  Ankara  20260130             63          4.85             11 -6.15   gfs
270  Ankara  20260130             57          4.85             11 -6.15   gfs
274  Ankara  20260130             51          6.85             11 -4.15   gfs
277  Ankara  20260130             45          6.85             11 -4.15   gfs
281  Ankara  20260130             33          4.85             11 -6.15   gfs
284  Ankara  20260130             27          5.85             11 -5.15   gfs
286  Ankara  20260130             21          5.85             11 -5.15   gfs
288  Ankara  20260130             15          5.85             11 -5.15   gfs
290  Ankara  20260130              9          5.85             11 -5.15   gfs
292  Ankara  20260130              3          4.85             11 -6.15   gfs

In [1]:
import xarray as xr
df = xr.open_dataset("/mnt/ssd/gfs_archive/2021010100/gfs_2021010100_f000.grib2")

skipping variable: paramId==165 shortName='u10'
Traceback (most recent call last):
  File "/home/gkbrkgrr/miniconda3/envs/env_poly/lib/python3.14/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gkbrkgrr/miniconda3/envs/env_poly/lib/python3.14/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==166 shortName='v10'
Traceback (most recent call last):
  File "/home/gkbrkgrr/miniconda3/envs/env_poly/lib/python3.14/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gkbrkgrr/miniconda3/envs/env_poly/lib/python3.14/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))